### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by staggindraggin** [GandaG/relinker#2]
Every time I run the program I get the following:

Alright, let's get started.

First, search the Mods folder for merged plugins.
              Mod list parsed: [##################################################] 100.0% Done
                     Progress: [##################################################] 100.0% Done
Found merges at Realistic Water Two Merged
Found merges at Even Better Quest Objectives Patches Merged
Found merges at Legacy of the Dragonborn Patches Merge
Found merges at Weapon and Armor Attributes Patches Merged
Found merges at CACO Patches Merged
Found merges at Advanced Adversary Encounters Patches Merged
Found merges at Hunterborn Patches Merged
Found merges at Audio Overhaul for Skyrim Pacthes Merged
Found merges at Arthmoor's Settlements
Found merges at Small Location Merge
Found merges at Populated Skyrim Redone
Found merges at MLU Patches Merged
Found merges at Scrimshaw Expanded Patches Merged

Process merge maps.
                     Progress: [##########################################--------] 84.62% Done  File "<string>", line 276, in <module>

<class 'IndexError'>: list index out of range
Press Enter to exit...

What is going on and how do I fix it?

**Comment by GandaG** [comment]
Could you upload your merge maps to pastebin and post the links here?

If you don't know what they are, under each of those mod folders listed you'll find a "merge" folder and inside you'll see a file ending in "_map.txt" with the merge plugin's name as the start.

**Comment by staggindraggin** [comment]
Yeah sure no problem. http://pastebin.com/tjMvLZYe

**Comment by GandaG** [comment]
Does this part http://pastebin.com/EG5dmCVb really appear in your Populated Skyrim Redone merge map?

I LITERALLY have no idea how that got there, I even got experts on this to be sure something wasn't wrong. Rebuild the merge, try again and let me know how it went

**Comment by staggindraggin** [comment]
I rebuilt the merge and it looks like it's working! No idea how that wound up in my merge. Thanks man!

**Comment by GandaG** [comment]
Awesome! Anything else just open another ticket. Glad to have helped
