### ISSUE TITLE
Re-Linker failure regarding mintymcmpatchquestscript.pex

### ISSUE THREAD

**Issue by jdsmith2816** [GandaG/relinker#3]
Re-Linker is failing to properly relink mintymcmpatchquestscript.pex causing main menu crash on launch.

All relevant files are located at:

https://www.dropbox.com/sh/ka3rmpqejsveoaf/AACdGqYt3y3jmj7Qc5OGKvo9a?dl=0

**Comment by hishutup** [comment]
After spending awhile looking at this, it seems like a unique case but probably can be avoided.
Ganda rebuilds the string table which should be identical but for some reason changes the length of one particular string.
http://i.imgur.com/JrEUBFr.png
In the original source here is a snip.
`	self.AddHeaderOption("$Thanks", 0)
	self.AddTextOption("Jim", "©?©K??©??®", self.OPTION_FLAG_DISABLED)
	self.AddTextOption("Darren", "Jet-Set-Willy", self.OPTION_FLAG_DISABLED)
	self.AddTextOption("Lewis", "Lugar", self.OPTION_FLAG_DISABLED)`

**Comment by GandaG** [comment]
Fixed at 980a888df04edcb67913b235c237e786078792df
