### ISSUE TITLE
Error after applying merging maps

### ISSUE THREAD

**Issue by npower10** [GandaG/relinker#4]
Stop at 0.03% exactly here the detailed error in image:

![bandicam 2016-11-06 17-54-31-864](https://cloud.githubusercontent.com/assets/23265986/20039774/234b2694-a44a-11e6-85d9-d12a89ed3e4a.jpg)
![bandicam 2016-11-06 17-54-15-777](https://cloud.githubusercontent.com/assets/23265986/20039775/234d748a-a44a-11e6-9df3-7d845f4f92ef.jpg)

i can send you my load order if you want,i have all the tools requirement,mator merge standalone software,papyrus compiler and the patch,have selected all the possible option in mator's software,sorry its my first time in github and also first time reporting,also im a novice developer,sorry again for the inconvenience,also sorry im not native english...but still can understand it ^^ here my gmail: thunderbat999@gmail.com  ,send me a mail if you want my load order (its really big....) and also my merged mods for testing...also,im on discord on the nexus server with the same name as in the github,also,great job mate for this wonderful software^^

**Comment by GandaG** [comment]
Welcome to github :) Have you tried running skyrim? Does it even work? That error seems that the script is invalid.

If you're able to successfully run skyrim, try decompiling your scripts with champollion and check if there any errors.

**Comment by npower10** [comment]
i tried merging 255 mods together,skyrim work without merging them,but after that,even after a lot of cleaning,it don't work,maybe there a limit of how many you can merge together...also,i know there a limit of strings in mods with script,i think its 512 or something like this,and with the mator software the merge files detect that it have reach the limit,its 90000 strings for the final merge,maybe its also at fault for error,also,the folder in your relinker won't generate again,even if i remove everything and type corretly,and try to merge 2 little mods without any error...it gave the same error whatever i do...also,it would be nice if you integer a memory for the location of skyrim so user don't have to retype everytime or maybe just allow user to copy paste,cuz it won't...

**Comment by npower10** [comment]
also,and finaly,it would be nice if you can integer an extracter for esp and esm so if there error or incompatibility,your software can generate something similar for the bsa...

**Comment by GandaG** [comment]
If you type nothing and press enter relinker will use whatever is within the brackets. I did not nderstand the rest though :/ what about plugins?

**Comment by npower10** [comment]
the plugins are all little mods that add most of them 1 or 2 items like spell or/and armor,it work fine without merging,like i said,i checked them in loot and tes5edit,do some cleaning,removing deleted record and navmeshes like i do everytimes,but still continue to give the same error,also,i know that your software use "whatever is within the brackets" like you said because i noticed when he said "found merge..." and i conclude that you made it so he can select only mods with the tag "merge ..." by the software of Mator the great...so,i tried to remove all the mods in the Mod Organizer section,try merging two mods that i have tested with great success with your software,it's campfire and frostfall separate version,the newest at the current date,i name it whatever name like frostfire.esp,and it worked !!!!! :+1:  but its just the first time i used it so,like i said i retest the same exact files and without nothing other that these two mods in the mods folder of M.O and merge them with all the right option i did earlier when tested it the first time...and it gave me the same error...and also the folder created by the relinker remove itself when i launch it the last time after the first successful merge between frostfall and campfire...i also redo everything but outside M.O...so,now,i don't know what to think...

**Comment by npower10** [comment]
*update:sorry,it appear to work now that i like you said:" type nothing and press enter relinker will use whatever is within the brackets"...and it worked :+1: :+1: :+1:  i just do this outside M.O and shazam...the magic appear...

**Comment by npower10** [comment]
also i used the 64bit version of the relinker...outside M.O like i said...thanks again ^^

**Comment by GandaG** [comment]
So is it working now?

**Comment by npower10** [comment]
yeah perfectly ^^ i just launch the 64bit version instead of the 32bit one,outside of M.O this time,press enter 2 times like you said instead of retyping all the directory,and yeah no error at all ^^ i can send you the  pic if you want ^^

**Comment by npower10** [comment]
but i still don't know if there some limit of mods (plugins) you can merge (if they don't have any error or incompatibility,of course) like the string limit that appear when i merge a lot of mods together...

**Comment by GandaG** [comment]
That was in the instructions all along :) Relinker has nothing to do with merging mods, only the merges and their scripts, you should ask mator that. Closing since issue has been fixed.
