### ISSUE TITLE
Codec error

### ISSUE THREAD

**Issue by VoltaicJake** [GandaG/relinker#5]
While applying merge maps I get

![](http://puu.sh/sk1xT/2c7041097e.png)

Looks like you might have fixed this in a recent commit, but it isn't released?
Thanks!

**Comment by GandaG** [comment]
Can you try [this build](https://a.uguu.se/vssEzMknjCAx_Relinker.7z)?

**Comment by VoltaicJake** [comment]
It worked! Thank you so much. I need to learn python one of these days.
